export const TYPES = {
  Server: {
    Fastify: Symbol.for('FastifyServer'),
  },
  Prisma: {
    Client: Symbol.for('PrismaClient'),
    UnitOfWork: Symbol.for('PrismaUnitOfWork'),
  },
  Repositories: {
    User: Symbol.for('UserRepository'),
    Gym: Symbol.for('GymRepository'),
    CheckIn: Symbol.for('CheckInRepository'),
  },
  PG: {
    Client: Symbol.for('PgClient'),
    User: Symbol.for('PgUserRepository'),
    Gym: Symbol.for('PgGymRepository'),
    CheckIn: Symbol.for('PgCheckInRepository'),
  },
  Controllers: {
    CreateUser: Symbol.for('UserController'),
    Authenticate: Symbol.for('AuthenticateController'),
    UserProfile: Symbol.for('UserProfileController'),
    CheckIn: Symbol.for('CheckInController'),
    CreateGym: Symbol.for('CreateGymController'),
    UserMetrics: Symbol.for('UserMetricsController'),
    SearchGym: Symbol.for('SearchGymController'),
    ValidateCheckIn: Symbol.for('ValidateCheckInController'),
    MyProfile: Symbol.for('MyProfileController'),
    RefreshToken: Symbol.for('RefreshTokenController'),
    Queue: Symbol.for('QueueController'),
    ChangePassword: Symbol.for('ChangePasswordController'),
    FetchUsers: Symbol.for('FetchUsersController'),
    UpdateUserProfile: Symbol.for('UpdateUserProfileController'),
    ActivateUser: Symbol.for('ActivateUserController'),
  },
  UseCases: {
    CreateUser: Symbol.for('CreateUserUserCase'),
    Authenticate: Symbol.for('AuthenticateUseCase'),
    UserProfile: Symbol.for('UserProfileUseCase'),
    CreateGym: Symbol.for('CreateGymUseCase'),
    CheckIn: Symbol.for('CheckInUseCase'),
    CheckInHistory: Symbol.for('CheckInHistoryUseCase'),
    UserMetrics: Symbol.for('UserMetricsUseCase'),
    SearchGym: Symbol.for('SearchGymUseCase'),
    FetchNearbyGym: Symbol.for('FetchNearbyGymUseCase'),
    ValidateCheckIn: Symbol.for('ValidateCheckInUseCase'),
    Metrics: Symbol.for('MetricsUseCase'),
    ChangePassword: Symbol.for('ChangePasswordUseCase'),
    FetchUsers: Symbol.for('FetchUsersUseCase'),
    UpdateUserProfile: Symbol.for('UpdateUserProfileUseCase'),
    SuspendUser: Symbol.for('SuspendUserUseCase'),
    ActiveUser: Symbol.for('ActiveUserUseCase'),
  },
  Tokens: {
    Auth: Symbol.for('AuthToken'),
  },
  Cookies: {
    Manager: Symbol.for('CookieManager'),
  },
  Factories: {
    PreHandlerAuthenticate: Symbol.for('PreHandlerAuthenticate'),
  },
  DAO: {
    User: Symbol.for('UserDAO'),
  },
  Logger: Symbol.for('Logger'),
  Queue: Symbol.for('Queue'),
  Mailer: Symbol.for('Mailer'),
  Redis: Symbol.for('Redis'),
  UnitOfWork: Symbol.for('UnitOfWork'),
}
