@baseUrl = http://localhost:80
@userName = "João Silva"
@email = "joaos.silva190@example.com"
@password = "senha123"
// MEMBER ou ADMIN
@role = "ADMIN"

### Criar Usuário
# @name createUser
POST {{baseUrl}}/users
Content-Type: application/json

{
  "name": {{userName}},
  "email": {{email}},
  "password": "senha123",
  "role": {{role}}
}

### Autenticar Usuário
# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "email": "joao.silva@example.com",
  "password": "senha123"
}

###
@refreshToken = {{authenticate.response.body.refreshToken}}

# @name refresh
PATCH {{baseUrl}}/sessions/refresh
Content-Type: application/json
Cookie: refreshToken={{refreshToken}}

{
  
}

### Perfil
# @name userProfile
GET {{baseUrl}}/users?limit=10&page=1
Content-Type: application/json

{

}


### Criar Academia
# @name createGym
POST {{baseUrl}}/gyms
Content-Type: application/json
Authorization: Bearer {{authenticate.response.body.token}}

{
  "title": "Academia do João",
  "description": "Academia completa",
  "phone": "123456789",
  "latitude": -23.563099,
  "longitude": -46.656571
}