@baseUrl = http://localhost:80
@userName = "João Silva"
@email = "joao2s2ssssssssssssssssdssssssssssssssssssssdssssssss.silva@example.com"
@password = "senha123"
// MEMBER ou ADMIN
@role = "ADMIN"

### Criar Usuário
# @name createUser
POST {{baseUrl}}/users
Content-Type: application/json

{
  "name": {{userName}},
  "email": {{email}},
  "password": "senha123",
  "role": {{role}}
}

### Autenticar Usuário
# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "email": "joao1.silva@example.com",
  "password": "senha123"
}

###
@refreshToken = {{authenticate.response.body.refreshToken}}

# @name refresh
PATCH {{baseUrl}}/sessions/refresh
Content-Type: application/json
Cookie: refreshToken={{refreshToken}}

{
  
}

### Perfil
# @name userProfile
GET {{baseUrl}}/users?limit=10&page=1
Content-Type: application/json

{

}


### Criar Academia
# @name createGym
POST {{baseUrl}}/gyms
Content-Type: application/json
Authorization: Bearer {{authenticate.response.body.token}}

{
  "cnpj": "11.222.333/0001-81",
  "title": "Academia do João",
  "description": "Academia completa",
  "phone": "123456789",
  "latitude": -23.563099,
  "longitude": -46.656571
}

### Criar CheckIn
# @name createCheckIn
POST {{baseUrl}}/check-ins
Content-Type: application/json
Authorization: Bearer {{authenticate.response.body.token}}

{
  "userId": "4e6e3301-304d-4333-a5b7-01e469d9b484",
  "gymId": "54adf7d1-eed3-4416-bc0e-1cd56401cf35",
  "userLatitude": -23.563099,
  "userLongitude": -46.656571
}

### Ativar Usuário
# @name activateUser
PATCH {{baseUrl}}/users/activate
Content-Type: application/json

{
  "userId": "f47ac10b-58cc-4372-a567-0e02b2c3d479"
}

### Logout Usuário
# @name logout  
POST {{baseUrl}}/sessions/logout
Content-Type: application/json
Authorization: Bearer {{authenticate.response.body.token}}

{
  
}

### Health Check
# @name healthCheck
GET {{baseUrl}}/health-check
Content-Type: application/json

{
  
}