services:
  postgresql:
    container_name: postgress
    image: bitnami/postgresql:latest
    volumes:
      - postgresql_data:/bitnami/postgresql
    environment:
      - POSTGRES_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=apisolid
    ports:
      - 5432:5432

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672

  redis:
    container_name: redis
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    command: ['redis-server', '--appendonly', 'yes']

volumes:
  postgresql_data:
  redis_data:
