services:
  postgresql:
    container_name: postgress
    image: bitnami/postgresql:latest
    volumes:
      - postgresql_data:/bitnami/postgresql
    environment:
      - POSTGRES_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=apisolid
    ports:
      - 5432:5432

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672

volumes:
  postgresql_data:
