export const USER_TYPES = {
	Repositories: {
		User: Symbol.for("UserRepository"),
		UserActivity: Symbol.for("UserActivityRepository"),
	},
	PG: {
		User: Symbol.for("PgUserRepository"),
	},
	UseCases: {
		CreateUser: Symbol.for("CreateUserUseCase"),
		UpdateUser: Symbol.for("UpdateUserUseCase"),
		DeleteUser: Symbol.for("DeleteUserUseCase"),
		FetchUsers: Symbol.for("FetchUsersUseCase"),
		UserProfile: Symbol.for("UserProfileUseCase"),
		ChangePassword: Symbol.for("ChangePasswordUseCase"),
		CreatePasswordReauthGrant: Symbol.for("CreatePasswordReauthGrantUseCase"),
		DefinePassword: Symbol.for("DefinePasswordUseCase"),
		ForgotPassword: Symbol.for("ForgotPasswordUseCase"),
		ResetPassword: Symbol.for("ResetPasswordUseCase"),
		ActivateUser: Symbol.for("ActivateUserUseCase"),
		UpdateMyProfile: Symbol.for("UpdateMyProfileUseCase"),
		UpdateUserProfile: Symbol.for("UpdateUserProfileUseCase"),
		SuspendUser: Symbol.for("SuspendUserUseCase"),
		BulkChangeUserStatus: Symbol.for("BulkChangeUserStatusUseCase"),
		PromoteToAdmin: Symbol.for("PromoteToAdminUseCase"),
		DemoteFromAdmin: Symbol.for("DemoteFromAdminUseCase"),
		UserMetrics: Symbol.for("UserMetricsUseCase"),
		GetUserStats: Symbol.for("GetUserStatsUseCase"),
		GetUserActivity: Symbol.for("GetUserActivityUseCase"),
	},
	Controllers: {
		CreateUser: Symbol.for("UserController"),
		UserProfile: Symbol.for("UserProfileController"),
		ChangePassword: Symbol.for("ChangePasswordController"),
		CreatePasswordReauthGrant: Symbol.for(
			"CreatePasswordReauthGrantController",
		),
		DefinePassword: Symbol.for("DefinePasswordController"),
		ForgotPassword: Symbol.for("ForgotPasswordController"),
		ResetPassword: Symbol.for("ResetPasswordController"),
		FetchUsers: Symbol.for("FetchUsersController"),
		UpdateUserProfile: Symbol.for("UpdateUserProfileController"),
		ActivateUser: Symbol.for("ActivateUserController"),
		SuspendUser: Symbol.for("SuspendUserController"),
		BulkActivateUsers: Symbol.for("BulkActivateUsersController"),
		BulkDeactivateUsers: Symbol.for("BulkDeactivateUsersController"),
		MyProfile: Symbol.for("MyProfileController"),
		UpdateMyProfile: Symbol.for("UpdateMyProfileController"),
		UserMetrics: Symbol.for("UserMetricsController"),
		PromoteToAdmin: Symbol.for("PromoteToAdminController"),
		DemoteFromAdmin: Symbol.for("DemoteFromAdminController"),
		GetUserStats: Symbol.for("GetUserStatsController"),
		DeleteUser: Symbol.for("DeleteUserController"),
		GetUserActivity: Symbol.for("GetUserActivityController"),
		GetMyActivity: Symbol.for("GetMyActivityController"),
	},
	Gateways: {
		PasswordResetTokenStore: Symbol.for("PasswordResetTokenStore"),
		LoginAttemptStore: Symbol.for("LoginAttemptStore"),
	},
	DAO: {
		User: Symbol.for("UserDAO"),
		UserActivity: Symbol.for("UserActivityDao"),
	},
	Notifications: {
		SendWelcomeEmail: Symbol.for("SendWelcomeEmailNotification"),
		SendPasswordAlertEmail: Symbol.for("SendPasswordAlertEmailNotification"),
		SendPasswordResetEmail: Symbol.for("SendPasswordResetEmailNotification"),
		SendAccountLockedEmail: Symbol.for("SendAccountLockedEmailNotification"),
	},
	EventHandlers: {
		RecordUserActivity: Symbol.for("RecordUserActivitySubscriber"),
	},
} as const
