name: CI - Testes de Unidade

on: pull_request

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configuração do Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Instalação de dependências
        run: npm ci

      - name: Executar testes de unidade
        run: npm run test
